# Financial Chatbot - Alex
# Offline rule-based personal finance assistant

import json
import os
from datetime import datetime

DATA_FILE = "financial_data.json"

TOPICS = {
    "budgeting": "Budgeting is the process of planning income and expenses so you can control spending and work toward financial goals.",
    "savings": "Savings are money set aside for future needs, emergencies, and financial goals.",
    "investment": "Investment means putting money into assets such as stocks, bonds, or mutual funds with the expectation of earning returns. Investments involve risk.",
    "emi": "EMI stands for Equated Monthly Instalment. It is a periodic loan payment containing principal and interest.",
    "interest": "Interest is the cost of borrowing money or the return earned on savings or investments.",
    "tax": "Tax is a compulsory financial charge collected by the government. Actual tax liability depends on applicable laws and individual circumstances.",
    "credit": "Credit is the ability to borrow money or obtain goods and services with an agreement to repay later.",
    "credit score": "A credit score is a numerical indicator based on credit-history information such as repayment behaviour and credit utilisation.",
    "inflation": "Inflation is a sustained increase in the general price level of goods and services, reducing purchasing power over time.",
    "expenses": "Expenses are costs incurred for goods and services such as food, rent, transportation, education, and entertainment.",
    "financial planning": "Financial planning involves managing income, expenses, savings, investments, insurance, and goals for long-term financial stability.",
    "mutual funds": "A mutual fund pools money from multiple investors and invests it according to a defined strategy. Mutual funds are subject to investment risk.",
    "stocks": "Stocks represent ownership in a company. Returns may come from price appreciation or dividends, while losses are also possible.",
    "compound interest": "Compound interest is calculated on the original principal plus accumulated interest.",
    "simple interest": "Simple interest is calculated only on the original principal amount.",
    "loan": "A loan is money borrowed from a lender and repaid according to agreed terms, usually with interest.",
    "risk": "Financial risk is the possibility that a financial decision or investment may result in loss.",
    "diversification": "Diversification means spreading investments across different assets or categories to reduce concentration risk.",
    "returns": "Investment return is the gain or loss generated by an investment over a period.",
    "insurance": "Insurance provides financial protection against specified risks in exchange for a premium, subject to policy terms.",
    "retirement": "Retirement planning involves saving and investing to meet financial needs after regular employment income decreases or stops.",
    "liquidity": "Liquidity describes how quickly an asset can be converted into cash without a significant loss in value.",
    "net worth": "Net worth is total assets minus total liabilities.",
    "emergency fund": "An emergency fund is money kept aside for unexpected expenses or temporary income disruption.",
    "financial literacy": "Financial literacy is the ability to understand and use concepts such as budgeting, saving, borrowing, investing, insurance, and risk management."
}

def load_data():
    default = {"income": 0.0, "expenses": [], "savings_goal": None}
    if not os.path.exists(DATA_FILE):
        return default
    try:
        with open(DATA_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return default

def save_data(data):
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4)

def get_float(prompt, positive=False):
    while True:
        try:
            value = float(input(prompt))
            if value < 0 or (positive and value == 0):
                print("Please enter a valid positive amount.")
                continue
            return value
        except ValueError:
            print("Please enter a valid number.")

def get_int(prompt):
    while True:
        try:
            value = int(input(prompt))
            if value > 0:
                return value
            print("Enter a value greater than 0.")
        except ValueError:
            print("Enter a valid whole number.")

def show_help():
    return """
================ FINANCIAL CHATBOT HELP ================

General:
  help                  Show commands
  topics                Show finance topics
  about                 About Alex
  clear                 Clear screen
  exit                  Quit

Financial information:
  what is <topic>
  explain <topic>
  ask <topic>

Calculators:
  calculate emi
  calculate simple interest
  calculate compound interest
  calculate savings
  calculate inflation
  calculate net worth

Personal finance:
  set income
  add expense
  show expenses
  expense summary
  budget
  set savings goal
  show savings goal
  financial summary

=========================================================
"""

def show_topics():
    return "Available finance topics:\n" + "\n".join("- " + x.title() for x in TOPICS)

def about():
    return """Alex is an offline Financial Chatbot for personal-finance awareness.
It uses a local rule-based knowledge base and financial calculators.
No paid API or internet connection is required.

This project is for educational and financial-awareness purposes and
does not replace advice from a qualified financial professional."""

def emi():
    print("\n---------- EMI CALCULATOR ----------")
    p = get_float("Loan amount (₹): ", True)
    annual = get_float("Annual interest rate (%): ")
    months = get_int("Tenure (months): ")
    r = annual / 12 / 100
    if r == 0:
        payment = p / months
    else:
        factor = (1 + r) ** months
        payment = p * r * factor / (factor - 1)
    total = payment * months
    return f"Loan: ₹{p:,.2f}\nMonthly EMI: ₹{payment:,.2f}\nTotal payment: ₹{total:,.2f}\nTotal interest: ₹{total-p:,.2f}"

def simple_interest():
    print("\n------ SIMPLE INTEREST ------")
    p = get_float("Principal (₹): ", True)
    r = get_float("Annual rate (%): ")
    t = get_float("Time (years): ", True)
    interest = p * r * t / 100
    return f"Principal: ₹{p:,.2f}\nInterest: ₹{interest:,.2f}\nFinal amount: ₹{p+interest:,.2f}"

def compound_interest():
    print("\n------ COMPOUND INTEREST ------")
    p = get_float("Principal (₹): ", True)
    r = get_float("Annual rate (%): ")
    t = get_float("Time (years): ", True)
    n = get_int("Compounding periods per year: ")
    amount = p * (1 + r / 100 / n) ** (n * t)
    return f"Principal: ₹{p:,.2f}\nCompound interest: ₹{amount-p:,.2f}\nFinal amount: ₹{amount:,.2f}"

def savings_calc():
    print("\n---------- SAVINGS CALCULATOR ----------")
    income = get_float("Monthly income (₹): ", True)
    expenses = get_float("Monthly expenses (₹): ")
    saving = income - expenses
    rate = saving / income * 100
    return f"Income: ₹{income:,.2f}\nExpenses: ₹{expenses:,.2f}\nSavings/surplus: ₹{saving:,.2f}\nSavings rate: {rate:.2f}%"

def inflation_calc():
    print("\n---------- INFLATION CALCULATOR ----------")
    value = get_float("Current amount/value (₹): ", True)
    rate = get_float("Annual inflation rate (%): ")
    years = get_float("Years: ", True)
    future = value * (1 + rate / 100) ** years
    return f"Current value: ₹{value:,.2f}\nEstimated future cost: ₹{future:,.2f}"

def net_worth():
    print("\n---------- NET WORTH CALCULATOR ----------")
    assets = get_float("Total assets (₹): ")
    liabilities = get_float("Total liabilities (₹): ")
    return f"Assets: ₹{assets:,.2f}\nLiabilities: ₹{liabilities:,.2f}\nNet worth: ₹{assets-liabilities:,.2f}"

def set_income(data):
    data["income"] = get_float("\nMonthly income (₹): ", True)
    save_data(data)
    return f"Monthly income saved: ₹{data['income']:,.2f}"

def add_expense(data):
    print("\n---------- ADD EXPENSE ----------")
    amount = get_float("Amount (₹): ", True)
    category = input("Category (food/rent/travel/etc.): ").strip().lower() or "other"
    description = input("Description: ").strip() or "No description"
    data["expenses"].append({
        "amount": amount, "category": category,
        "description": description,
        "date": datetime.now().strftime("%Y-%m-%d %H:%M")
    })
    save_data(data)
    return f"Expense added: ₹{amount:,.2f} | {category}"

def show_expenses(data):
    if not data["expenses"]:
        return "No expenses recorded yet."
    lines = ["\n--------------- EXPENSES ---------------"]
    total = 0
    for i, e in enumerate(data["expenses"], 1):
        total += e["amount"]
        lines.append(f"{i}. ₹{e['amount']:,.2f} | {e['category'].title()} | {e['description']} | {e['date']}")
    lines.append(f"Total expenses: ₹{total:,.2f}")
    return "\n".join(lines)

def expense_summary(data):
    totals = {}
    for e in data["expenses"]:
        totals[e["category"]] = totals.get(e["category"], 0) + e["amount"]
    if not totals:
        return "No expenses recorded yet."
    lines = ["\n---------- EXPENSE SUMMARY ----------"]
    for category, amount in sorted(totals.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"{category.title()}: ₹{amount:,.2f}")
    return "\n".join(lines)

def budget(data):
    income = data["income"]
    total = sum(e["amount"] for e in data["expenses"])
    if income <= 0:
        return "No income recorded. Use 'set income' first."
    balance = income - total
    ratio = total / income * 100
    return (f"\n---------- BUDGET SUMMARY ----------\n"
            f"Income: ₹{income:,.2f}\nExpenses: ₹{total:,.2f}\n"
            f"Balance: ₹{balance:,.2f}\nExpense ratio: {ratio:.2f}%\n"
            + ("Expenses exceed income. Review spending." if balance < 0
               else "You have a positive balance. Consider allocating part of it to savings."))

def set_goal(data):
    print("\n---------- SAVINGS GOAL ----------")
    name = input("Goal name: ").strip() or "My Savings Goal"
    target = get_float("Target amount (₹): ", True)
    saved = get_float("Already saved (₹): ")
    data["savings_goal"] = {"name": name, "target": target, "saved": saved}
    save_data(data)
    return f"Goal saved: {name}\nTarget: ₹{target:,.2f}\nSaved: ₹{saved:,.2f}\nRemaining: ₹{max(target-saved,0):,.2f}"

def show_goal(data):
    g = data.get("savings_goal")
    if not g:
        return "No savings goal set. Use 'set savings goal'."
    progress = min(g["saved"] / g["target"] * 100, 100)
    return f"Goal: {g['name']}\nTarget: ₹{g['target']:,.2f}\nSaved: ₹{g['saved']:,.2f}\nRemaining: ₹{max(g['target']-g['saved'],0):,.2f}\nProgress: {progress:.2f}%"

def summary(data):
    income = data["income"]
    expenses = sum(e["amount"] for e in data["expenses"])
    balance = income - expenses
    goal = data.get("savings_goal")
    result = f"\n========== FINANCIAL SUMMARY ==========\nIncome: ₹{income:,.2f}\nExpenses: ₹{expenses:,.2f}\nBalance: ₹{balance:,.2f}\n"
    result += f"Savings goal: {goal['name']}\n" if goal else "Savings goal: Not set\n"
    return result

def find_topic(text):
    text = text.lower().strip()
    if text in TOPICS:
        return text
    for topic in sorted(TOPICS, key=len, reverse=True):
        if topic in text:
            return topic
    return None

def response(user, data):
    u = user.lower().strip()

    if u in {"help", "commands", "help commands"}: return show_help()
    if u in {"topics", "help topics"}: return show_topics()
    if u == "about": return about()
    if u in {"calculate emi", "emi calculator", "emi"}: return emi()
    if u in {"calculate simple interest", "simple interest calculator", "simple interest"}: return simple_interest()
    if u in {"calculate compound interest", "compound interest calculator", "compound interest"}: return compound_interest()
    if u in {"calculate savings", "savings calculator"}: return savings_calc()
    if u in {"calculate inflation", "inflation calculator"}: return inflation_calc()
    if u in {"calculate net worth", "net worth calculator", "net worth"}: return net_worth()
    if u in {"set income", "add income"}: return set_income(data)
    if u in {"add expense", "record expense"}: return add_expense(data)
    if u in {"show expenses", "expenses", "expense list"}: return show_expenses(data)
    if u in {"expense summary", "expense categories", "categories"}: return expense_summary(data)
    if u in {"budget", "budget summary", "my budget"}: return budget(data)
    if u in {"set savings goal", "create savings goal"}: return set_goal(data)
    if u in {"show savings goal", "savings goal"}: return show_goal(data)
    if u in {"financial summary", "summary", "my financial summary"}: return summary(data)

    topic = find_topic(u)
    if topic:
        return TOPICS[topic]

    if u in {"hi", "hello", "hey", "hii", "hiii"}:
        return "Hello! 👋 I am Alex, your Financial Chatbot. Type 'help' to see what I can do."

    return ("I couldn't match that to my financial knowledge base. "
            "Try 'help' or 'topics', or ask about budgeting, savings, "
            "investment, EMI, loans, tax, insurance, credit, or inflation.")

def main():
    data = load_data()
    print("""
=========================================================
          🤖 ALEX - FINANCIAL CHATBOT
=========================================================
Offline Personal Finance Assistant

Type 'help'   → Show commands
Type 'topics' → Show finance topics
Type 'exit'   → Quit
=========================================================
""")
    while True:
        try:
            user = input("\nYou: ").strip()
            if user.lower() in {"exit", "quit", "bye"}:
                print("Alex: Goodbye! 👋")
                break
            if user.lower() == "clear":
                os.system("clear")
                continue
            print("\nAlex:", response(user, data))
        except (KeyboardInterrupt, EOFError):
            print("\nAlex: Goodbye! 👋")
            break

if __name__ == "__main__":
    main()
